# Use official Nginx image
FROM nginx:latest

# Copy HTML and CSS files to Nginx web directory
COPY form.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/style.css

# Expose port 80
EXPOSE 80
